# Generated by Django 4.1.4 on 2023-02-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Aron", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Events",
        ),
    ]
