# Generated by Django 4.1.4 on 2023-02-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aron", "0003_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("Date", models.DateTimeField(auto_now_add=True, null=True)),
                ("Description", models.CharField(max_length=1000, null=True)),
                ("Attendee", models.IntegerField(blank=True)),
                (
                    "eventImage",
                    models.ImageField(
                        blank=True, default="FOSSCUlogo.png", null=True, upload_to=""
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Events",
        ),
    ]
